// Generated by scripts/package-website-download.sh — do not edit by hand.
export const artifact = {
  version: '0.1.0',
  builtAt: '2026-07-12',
  commit: '0529d69',
  sha256: 'b39275e8553b497fe18695e76f0d49afc5cb058559e26f310660e0f53f5409fa',
  bytes: 2174482,
  architectures: 'x86_64 arm64',
} as const;
