import Testing
import KoruDomain
@testable import KoruPlatform

@Test func emptyFocusAloneNeverShowsPanel() { var session = FreshInputSession(); session.handle(.focus(value: "", selectionLocation: 0, selectionLength: 0, editable: true, secure: false, excluded: false)); #expect(session.state == .eligibleEmptyStart) }
@Test func qualifyingPrefixCanShowOnlyAfterVerifiedFreshFocus() { var session = FreshInputSession(); session.handle(.focus(value: "", selectionLocation: 0, selectionLength: 0, editable: true, secure: false, excluded: false)); session.handle(.committedCharacter("p", hasQualifyingMatch: false)); session.handle(.committedCharacter("u", hasQualifyingMatch: false)); session.handle(.committedCharacter("s", hasQualifyingMatch: true)); #expect(session.state == .panelVisible("pus")) }
@Test func nilValueWithCollapsedCaretAtZeroIsStillAVerifiedEmptyStart() { var session = FreshInputSession(); session.handle(.focus(value: nil, selectionLocation: 0, selectionLength: 0, editable: true, secure: false, excluded: false)); #expect(session.state == .eligibleEmptyStart) }
@Test func chromiumEmptyRichTextPlaceholderNewlineIsStillAVerifiedEmptyStart() {
    var session = FreshInputSession(); session.handle(.focus(value: "\n", selectionLocation: 0, selectionLength: 0, editable: true, secure: false, excluded: false)); #expect(session.state == .eligibleEmptyStart)
    var withText = FreshInputSession(); withText.handle(.focus(value: "x\n", selectionLocation: 0, selectionLength: 0, editable: true, secure: false, excluded: false)); #expect(withText.state == .ineligibleUntilFocusChanges)
    var caretPastZero = FreshInputSession(); caretPastZero.handle(.focus(value: "\n", selectionLocation: 1, selectionLength: 0, editable: true, secure: false, excluded: false)); #expect(caretPastZero.state == .ineligibleUntilFocusChanges)
}
@Test func midWritingNeverBecomesEligible() { var session = FreshInputSession(); session.handle(.focus(value: "existing", selectionLocation: 8, selectionLength: 0, editable: true, secure: false, excluded: false)); session.handle(.committedCharacter("p", hasQualifyingMatch: true)); #expect(session.state == .ineligibleUntilFocusChanges) }
@Test func secureAndUnknownContextsFailClosed() { var secure = FreshInputSession(); secure.handle(.focus(value: "", selectionLocation: 0, selectionLength: 0, editable: true, secure: true, excluded: false)); #expect(secure.state == .ineligibleUntilFocusChanges); var unknown = FreshInputSession(); unknown.handle(.focus(value: nil, selectionLocation: nil, selectionLength: nil, editable: true, secure: false, excluded: false)); #expect(unknown.state == .ineligibleUntilFocusChanges) }
@Test func dismissalDoesNotReopenUntilFocusChanges() { var session = FreshInputSession(); session.handle(.focus(value: "", selectionLocation: 0, selectionLength: 0, editable: true, secure: false, excluded: false)); session.handle(.committedCharacter("c", hasQualifyingMatch: false)); session.handle(.committedCharacter("l", hasQualifyingMatch: false)); session.handle(.committedCharacter("p", hasQualifyingMatch: false)); #expect(session.state == .panelVisible("clp")); session.handle(.dismiss); session.handle(.committedCharacter("x", hasQualifyingMatch: true)); #expect(session.state == .completedOrDismissed) }
