#!/usr/bin/env bash
# Packages the downloadable Koru app for the website.
#
# Builds (or reuses, when a bundle path is passed) the universal Release app,
# ad-hoc seals a staged copy so downloads launch after the expected Gatekeeper
# approval, zips it, and refreshes website/public/downloads plus the version
# manifest rendered on /download/. build-unsigned.sh and build-signed-local.sh
# run this automatically so the website copy always matches the latest build;
# set KORU_SKIP_WEBSITE_PACKAGE=1 to skip from those scripts.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
[[ -d Koru.xcodeproj ]] || { echo "Koru.xcodeproj is missing" >&2; exit 2; }

app="${1:-}"
if [[ -z "$app" ]]; then
  products="build/UnsignedProducts"
  xcodebuild -project Koru.xcodeproj -target Koru -configuration Release \
    CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO SWIFT_STRICT_CONCURRENCY=complete \
    ARCHS="arm64 x86_64" ONLY_ACTIVE_ARCH=NO CONFIGURATION_BUILD_DIR="$products" build >/dev/null
  app="$products/Koru.app"
fi
binary="$app/Contents/MacOS/Koru"
[[ -d "$app" && -x "$binary" ]] || { echo "App bundle not found at $app" >&2; exit 3; }

architectures="$(lipo -archs "$binary")"
[[ " $architectures " == *" arm64 "* && " $architectures " == *" x86_64 "* ]] || {
  echo "Website artifact must be universal; found: $architectures" >&2
  exit 4
}

# Seal a staged copy so the shipped bundle carries a consistent ad-hoc
# signature without mutating the build products directory.
staging="$(mktemp -d)"
trap 'rm -rf "$staging"' EXIT
ditto "$app" "$staging/Koru.app"
codesign --force --deep --sign - "$staging/Koru.app" 2>/dev/null
codesign --verify --strict "$staging/Koru.app"

out="website/public/downloads"
mkdir -p "$out"
rm -f "$out/Koru.zip"
ditto -c -k --sequesterRsrc --keepParent "$staging/Koru.app" "$out/Koru.zip"

version="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$app/Contents/Info.plist")"
sha="$(shasum -a 256 "$out/Koru.zip" | awk '{print $1}')"
bytes="$(stat -f%z "$out/Koru.zip")"
commit="$(git rev-parse --short HEAD)"
built_at="$(date -u +%Y-%m-%d)"
printf '%s  Koru.zip\n' "$sha" > "$out/Koru.zip.sha256"

# Regenerated on every packaging run; rendered on the /download/ page.
cat > website/src/content/download-artifact.ts <<TS
// Generated by scripts/package-website-download.sh — do not edit by hand.
export const artifact = {
  version: '$version',
  builtAt: '$built_at',
  commit: '$commit',
  sha256: '$sha',
  bytes: $bytes,
  architectures: '$architectures',
} as const;
TS

echo "Website download refreshed: $out/Koru.zip (v$version, $architectures, $bytes bytes)"
echo "sha256 $sha"
